accounts/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('',views.myAccount),
    path('registerUser/', views.registerUser, name='registerUser'),
    path('registerVendor/', views.registerVendor, name='registerVendor'),
    
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('myAccount/', views.myAccount, name='myAccount'),
    path('custDashboard/',views.custDashboard, name='custDashboard'),
    path('vendorDashboard/',views.vendorDashboard, name='vendorDashboard'),
    
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('reset_password_validate/<uidb64>/<token>/', views.reset_password_validate, name='reset_password_validate'),
    path('reset_password/', views.reset_password, name='reset_password'),
    path ('vendor/', include('vendor.urls')),
]

foodOnline_project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from marketplace import views as MarketplaceViews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('', include('accounts.urls')),
    
    path('marketplace/', include('marketplace.urls')),
    
    #CART
    path('cart/',MarketplaceViews.cart, name='cart'),
    #SEARCH
    path('search/',MarketplaceViews.search, name='search'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/forms.py
from django import forms
from .models import User, UserProfile
from .validators import allow_only_images_validator

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password']
        
    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')
        
        if password != confirm_password:
            raise forms.ValidationError(
                "Password does not match!"
            )
        
class UserProfileForm(forms.ModelForm):
    address = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'start typing...', 'required': 'required'}))
    profile_picture = forms.FileField(widget=forms.FileInput(attrs={'class' : 'btn btn-info'}), validators=[allow_only_images_validator])
    cover_photo = forms.FileField(widget=forms.FileInput(attrs={'class' : 'btn btn-info'}), validators = [allow_only_images_validator])
    
    
    latitude = forms.CharField(widget=forms.TextInput(attrs={'readonly' : 'readonly'}))
    longitude = forms.CharField(widget=forms.TextInput(attrs={'readonly' : 'readonly'}))
    class Meta:
        model = UserProfile
        fields = ['profile_picture', 'cover_photo', 'address', 'country', 'state', 'city', 'pin_code', 'latitude', 'longitude']

    #Another way of do readonly longitude and latitude 
    # def __init__(self, *args, **kwargs):
    #     super(UserProfileForm, self).__init__(*args, **kwargs)
    #     for field in self.fields:
    #         if field == 'latitude' or field == 'longitude':
    #             self.fields[field].widget.attrs['readonly'] = 'readonly'

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>FoodOnline</title>
	<!-- Google Font Family Link Start -->
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:400,700,800">
	<!-- Google Font Family Link End -->

	

	<!-- CSS -->
	<link href="{% static 'css/iconmoon.css' %}" rel="stylesheet">
	<link href="{% static 'css/style.css' %}" rel="stylesheet">
	<link href="{% static 'css/cs-foodbakery-plugin.css' %}" rel="stylesheet">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<link href="{% static 'css/cs-foodbakery-plugin.css' %}" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'css/custom.css' %}">
	
	{% comment %} Font awesome CDN {% endcomment %}
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


	<!-- JAVASCRIPT -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="{% static 'js/modernizr.js' %}"></script>
	<script src="{% static 'js/bootstrap.js' %}"></script>

	{% if '/profile/' in request.path %}
	<script src="https://maps.googleapis.com/maps/api/js?key={{GOOGLE_API_KEY}}&libraries=places&callback=initAutoComplete"  defer></script>
	{% endif %}

	{% comment %} Sweetalert {% endcomment %}
	<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
	<script src="{% static 'js/custom.js'%}"></script>

	<style>
		body, .main-section p, .mce-content-body p{
			font:Normal  14px/24px "Open Sans", sans-serif;letter-spacing: 0px;text-transform: none;color: #515151 !important;
		}
	</style>
</head>

<body>
    <!-- LOAD NAVBAR HERE-->
    {% include 'includes/navbar.html' %}

    <!--LOAD CONTENT HERE-->
    {% block content %}
        <!--CONTENT GOES HERE-->
        
    {% endblock %}

    <!--LOAD FOOTER HERE-->
    {% include 'includes/footer.html' %}
	

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- Main Section Start -->
<div class="main-section">
	<!-- Home Pages Elements Strat -->
	<!-- Main Search Start -->
	<div class="page-section nopadding cs-nomargin" style="padding-top: 200px; padding-bottom: 150px; margin-bottom: 0px; background: url({% static 'extra-images/bg-image1.jpg' %}) no-repeat center / cover;">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
					<div class="element-title">
						<h1 style="font-size: 40px; color: #505050; text-transform: uppercase; line-height: 50px; margin-bottom: 25px; text-align:center;">
							We are in the business of food<br>our restaurants do</h1>
						<p style="font-size: 18px; letter-spacing: 1px; color: #505050; text-align:center;">
							Ridiculus sociosqu
							cursus neque cursus curae ante scelerisque vehicula.</p>
					</div>
				</div>
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
					<div class="main-search fancy bg-holder">
						<form action="{% url 'search' %}" method="GET">
							<div class="row">
								<div class="col-lg-4 col-md-4 col-sm-3 col-xs-12">
									<div class="field-holder">
										<input type="text" name="keyword" placeholder="Resturant name or Food name">
									</div>
								</div>
								<div class="col-lg-4 col-md-4 col-sm-5 col-xs-12">
									<div class="field-holder">
										<ul>
											<li class="select-location">
												<div class="foodbakery-locations-fields-group foodbakery-focus-out">
													<span class="foodbakery-search-location-icon"><i class="icon-location"></i></span>
													
													<input type="text" name="address" class="location-field-text filter" id="id_address" required placeholder="All Locations">
													<input type="hidden" name="lat" value="" id="id_latitude">
													<input type="hidden" name="lng" value="" id="id_longitude">
												</div>
												
											</li>
										</ul>
									</div>
								</div>
								<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
									<select name="radius" id="radius" style="height:50px;" required>
										<option value="" selected>Choose Radius</option>
										<option value="5">5km</option>
										<option value="10">10km</option>
										<option value="15">15km</option>
										<option value="20">20km</option>
										<option value="25">25km</option>
										<option value="30">30km</option>
										<option value="35">35km</option>

									</select>
								</div>
								<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
									<div class="field-holder">
										<input type="submit" value="Search">
									</div>
								</div>
							</div>
						</form>
					</div>
				</div>
				
			</div>
		</div>
	</div>
	<!-- Main Search End -->
	
	<!-- Top Restarurants Section Start -->
	<div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 0px;margin-bottom: 0px;background: #ffffff;">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div class="element-title align-left">
						<h2>Top Restaurants</h2>
						<p>Explore restaurants, bars, and cafés by locality</p>
					</div>
				</div>
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" style="padding-right:0 !important; padding-left:0 !important;">
					<div class="company-logo">
						<ul>
							{% for vendor in vendors %}
							<li class="has-border">
								<figure>
									{% if vendor.user_profile.profile_picture %}
									<a href="{% url 'vendor_detail' vendor.vendor_slug %}"><img src="{{ vendor.user_profile.profile_picture.url }}" class="attachment-full size-full wp-post-image" alt=""></a>
									{% else %}
									<a href="{% url 'vendor_detail' vendor.vendor_slug %}"><img src="{% static 'images/default-profile.png' %}" class="attachment-full size-full wp-post-image" alt=""></a>
									{% endif %}
								</figure>
							</li>
							{% endfor %}
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Top Restarurants Section End -->
	<!-- Choose From Most Popular Listin Start -->
	<div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 50px;margin-bottom: 0px;background: #ffffff;">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div class="element-title align-center">
						<h2>Choose From Most Popular Restaurants</h2>
						<p>Cum doctus civibus efficiantur in imperdiet deterruisset.</p>
					</div>
				</div>
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div class="listing fancy">
						<ul class="row">
							{% for vendor in vendors %}
							<li class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
								<div class="list-post featured">
									<div class="img-holder">
										<figure>
											<a href="{% url 'vendor_detail' vendor.vendor_slug %}">
												{% if vendor.user_profile.profile_picture %}
												<img src="{{ vendor.user_profile.profile_picture.url }}" class="img-thumb wp-post-image" alt="">
												{% else %}
												<img src="{% static 'images/default-profile.png' %}" class="img-thumb wp-post-image" alt="">
												{% endif %}
											</a>
										</figure>
										<span class="restaurant-status close">
											<em class="bookmarkRibbon"></em>Close
										</span>
									</div>
									<div class="text-holder">
										
										<div class="post-title">
											<h5>
												<a href="{% url 'vendor_detail' vendor.vendor_slug %}">{{ vendor }}</a>
											</h5>
										</div>
										{% if vendor.user_profile.city and vendor.user_profile.state and vendor.user_profile.pin_code %}
										<span>{{ vendor.user_profile.city}}, {{ vendor.user_profile.state }}, {{ vendor.user_profile.pin_code }}</span>
										{% endif %}

										{% if vendor.kms %}
											<br>
										<span><small><b>{{vendor.kms}} km</b>Away</small></span>
										{% endif %}
									</div>
									
								</div>
							</li>
							{% endfor %}
							
							
							
							
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Choose From Most Popular Listing End -->

	<!-- Home Pages Elements End  -->
</div>
<!-- Main Section End -->
{% endblock %}